name: Build and update GitOps with ECR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "306667525254"
  ECR_REPOSITORY: devship-demo-app
  GITOPS_REPO: MiguelSilva04/devship-gitops

jobs:
  build-and-update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Define image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./app

      - name: Tag Docker image for ECR
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update image tag in GitOps manifest
        run: |
          GITOPS_PATH="apps/demo-app/${{ inputs.environment }}/backend-deployment.yaml"
          ECR_IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG"

          sed -i "s|image: .*devship-demo-app:.*|image: $ECR_IMAGE|g" gitops/$GITOPS_PATH

          echo "GITOPS_PATH=$GITOPS_PATH" >> $GITHUB_ENV
          echo "ECR_IMAGE=$ECR_IMAGE" >> $GITHUB_ENV

      - name: Commit and push GitOps change
        run: |
          cd gitops
          git config user.name "devship-github-actions"
          git config user.email "devship-actions@users.noreply.github.com"
          git add $GITOPS_PATH
          git commit -m "chore: deploy $ECR_IMAGE to ${{ inputs.environment }}" || echo "No changes to commit"
          git push
